### ISSUE TITLE
Introduction

### ISSUE THREAD

**Issue by Rnorback** [memiah/contact-tracer#2]
Hi @cmorillo and @paulmaunders , 

Very interested in helping with this effort. I'm a mobile developer. Specialize in iOS but also do cross-platform and have worked with bluetooth. Big concern of mine is that bluetooth can grab everyone in your apartment building (above and below you) so elevation comparisons would dramatically increase accuracy.

My email is RNorback [@] gmail.com. Would you mind adding me to the slack channel? I'd like to see how I can best jump in.

Looks like the code from Trace Together will be open sourced soon. One serious drawback is having to leave the app open. Would love to discuss further.

Best,
Rob

**Comment by paulmaunders** [comment]
I'll send you an invite now!
